// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7E4YdY5snJpJWFU6VKhbJJ
// Component: mEfuA7pkcwI_R
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import CopyableLink from "../../CopyableLink"; // plasmic-import: b07yO1uX9v0T7/component
import { useScreenVariants as useScreenVariantsbgVmM8VAaxo3Q } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: BgVmM8VAaxo3Q/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_minimalist_about_me_page.module.css"; // plasmic-import: 7E4YdY5snJpJWFU6VKhbJJ/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: mEfuA7pkcwI_R/css
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: DsgWeHyVmoDP8/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: S08tapsPSsZT8/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: GAQ9h61DiH9yx/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbgVmM8VAaxo3Q()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__dYk8F)}>
            <div className={classNames(projectcss.all, sty.freeBox__u8BCr)} />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__rjnjD)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__nXhg)}>
                <div className={classNames(projectcss.all, sty.freeBox__dnkcA)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fKd0U
                    )}
                  >
                    {"Anna Wu"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__noKUy
                    )}
                  >
                    {
                      "Building things for building things.\nDesign and code at Plasmic."
                    }
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__leUpx)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tn9R2
                  )}
                >
                  {" "}
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__wggxh)}>
                  <CopyableLink
                    data-plasmic-name={"copyableLink"}
                    data-plasmic-override={overrides.copyableLink}
                    className={classNames("__wab_instance", sty.copyableLink)}
                  >
                    {"aw@gmail.com"}
                  </CopyableLink>
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iGpEn)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___6NBx)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__uCU
                      )}
                      href={"https://www.twitter.com"}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__z04I1)}
                        role={"img"}
                      />
                    </a>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__lzbFd
                      )}
                      href={"https://www.dribbble.com"}
                    >
                      <Icon2Icon
                        className={classNames(projectcss.all, sty.svg__gcfJ)}
                        role={"img"}
                      />
                    </a>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___6FObn
                      )}
                      href={"https://www.github.com"}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__zr1L5)}
                        role={"img"}
                      />
                    </a>
                  </p.Stack>
                </p.Stack>
              </div>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__ivZ6)} />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "copyableLink"],
  copyableLink: ["copyableLink"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    copyableLink: makeNodeComponent("copyableLink"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
